server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pokemon_auth
    username: yx
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

app:
  jwt:
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_CHANGE_ME"
    accessMinutes: 15
    refreshDays: 14

frontend:
  origin: "http://localhost:3000"
