spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pokemon_auth}
    username: ${SPRING_DATASOURCE_USERNAME:yx}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    accessMinutes: ${APP_JWT_ACCESSMINUTES:15}
    refreshDays: ${APP_JWT_REFRESHDAYS:14}

frontend:
  origin: ${FRONTEND_ORIGIN:http://localhost:3000}
